### ISSUE TITLE
Crashes node-red

### ISSUE THREAD

**Issue by genepool99** [stephenkeep/node-red-contrib-orvibo#2]
When rapidly injecting 4-5 times into the ir emitter (with a valid IR code) I get:
14 Jan 20:02:18 - [red] Uncaught Exception:
14 Jan 20:02:18 - Error: write EIO
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)

Node: 7.2.0
Node-red:0.15.2

**Comment by genepool99** [comment]
Oops, wrong repo, meant to report in node-red-contrib-orvibo-allone.
